repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.354
    hooks:
      - id: pyright
        additional_dependencies: [
          "aiofiles==25.1.0",
          "aiogram==3.26.0",
          "aiohappyeyeballs==2.6.1",
          "aiohttp==3.13.3",
          "aiosignal==1.4.0",
          "annotated-types==0.7.0",
          "APScheduler==3.11.2",
          "attrs==25.4.0",
          "beautifulsoup4==4.14.3",
          "certifi==2026.2.25",
          "cfgv==3.5.0",
          "distlib==0.4.0",
          "filelock==3.25.0",
          "frozenlist==1.8.0",
          "identify==2.6.17",
          "idna==3.11",
          "lxml==6.0.2",
          "magic-filter==1.0.12",
          "multidict==6.7.1",
          "nodeenv==1.10.0",
          "platformdirs==4.9.4",
          "pre_commit==4.5.1",
          "propcache==0.4.1",
          "pydantic==2.12.5",
          "pydantic_core==2.41.5",
          "python-discovery==1.1.0",
          "python-dotenv==1.2.2",
          "PyYAML==6.0.3",
          "ruff==0.15.5",
          "soupsieve==2.8.3",
          "typing-inspection==0.4.2",
          "typing_extensions==4.15.0",
          "tzlocal==5.3.1",
          "virtualenv==21.1.0",
          "yarl==1.23.0"
        ]
